### PR TITLE
Additional V10 Fixes

### PR DESCRIPTION
**Pull request by sasquach45932**
Fixes:
No roll on embedded rolltables
Warning displayed in console

### CODE REVIEW

**Comment by Jmwhite45** [comment]
When trying to roll on a loot table I get the following error:
image

This is the exact location of the error:
image


I am trying to use this branch so that I can roll on a table from a table.
This is the manifest I am installing from: https://raw.githubusercontent.com/sasquach45932/better-rolltables/master/module.json
This is my setup:
Foundry V10, Build 290
DND5e 2.0.3

This is a table I am trying to roll on:
image
image

**Comment by sasquach45932** [comment]
Please use the correct [manifest](https://github.com/sasquach45932/better-rolltables/releases/download/final/module.json).

**Comment by chrisk123999** [comment]
Capture

Using this pull request still results in errors for me.

**Comment by sasquach45932** [comment]
> 
> Using this pull request still results in errors for me.

Try to uninstall and [install](https://github.com/sasquach45932/better-rolltables/releases/download/final/module.json) again. Please check the RollTable. If the Rolltable is not correct e.g. row is referencing to a missing entry in the dependent rolltable/compendium entry, it throws you an error message.

**Comment by chrisk123999** [comment]
That explains it.  I just updated to v10 and some of the compendiums I was referencing are not invalid.  Thanks.

**Review by elizeuangelo — APPROVED** [review]
Thank you for the updates! I will be releasing a new version soon

**Pull request merged**
